name: Build

on:
  release:
    types: [published, released]
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running as ${{ github.actor }} "
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
      - name: ts build
        run: |
          cd app
          npm ci
          npm run build

      - name: aws cred config
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{secrets.GHA_AWS_ROLE}}
          aws-region: ${{secrets.AWS_REGION}}
      - name: ecr login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: build and push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: tt-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
