name: Build

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running as ${{ github.actor }} "
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
      - name: ts build
        run: |
          cd app
          npm ci
          npm run build
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: build
        run: |
          docker build . -t tt
      - name: aws cred config
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{secrets.GHA_AWS_ROLE}}
          aws-region: ${{secrets.AWS_REGION}}
