name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
      - run: |
          cd app
          npm ci
          npm run build
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Build
        run: |
          docker build . -t tt
