name: Check code

on:
  push:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
      - name: ts build
        run: |
          cd app
          npm ci
          npm run build
      - name: eslint
        run: |
          cd app
          npx eslint
      - name: prettier
        run: |
          cd app
          npx prettier --check .
